"""GO ranks within a namespace, so the rank uniqueness must too

Revision ID: 33366736bf35
Revises: dce5957b7581
Create Date: 2026-09-04 20:58:24.876588
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '33366736bf35'
down_revision: str | None = 'dce5957b7581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_locus_annotation_entry__locus_id_annotation_kind_ran_b253'), 'locus_annotation_entry', type_='unique')
    op.create_index('uq_locus_annotation_entry__locus_kind_namespace_rank', 'locus_annotation_entry', ['locus_id', 'annotation_kind', sa.literal_column('COALESCE(gene_ontology_namespace, -1)'), 'rank_within_locus'], unique=True)
    op.create_check_constraint(op.f('ck_locus_annotation_entry__namespace_matches_kind'), 'locus_annotation_entry', "(annotation_kind = 'GENE_ONTOLOGY_SLIM') = (gene_ontology_namespace IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_locus_annotation_entry__namespace_matches_kind'), 'locus_annotation_entry', type_='check')
    op.drop_index('uq_locus_annotation_entry__locus_kind_namespace_rank', table_name='locus_annotation_entry')
    op.create_unique_constraint(op.f('uq_locus_annotation_entry__locus_id_annotation_kind_ran_b253'), 'locus_annotation_entry', ['locus_id', 'annotation_kind', 'rank_within_locus'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
