"""an architecture has no length bound and a cog category is a set

Revision ID: 4ee35b5568b6
Revises: 128186813705
Create Date: 2026-09-04 21:20:39.493337
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4ee35b5568b6'
down_revision: str | None = '128186813705'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locus', sa.Column('modal_cog_categories', postgresql.ARRAY(sa.String(length=1)), nullable=True))
    op.drop_column('locus', 'modal_cog_category')
    op.alter_column('locus_annotation_entry', 'term_value',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('locus_uniref_family_crosstab', 'modal_pfam_architecture',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locus_uniref_family_crosstab', 'modal_pfam_architecture',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('locus_annotation_entry', 'term_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.add_column('locus', sa.Column('modal_cog_category', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('locus', 'modal_cog_categories')
    # ### end Alembic commands ###
