"""the trigram index search was designed around

Revision ID: 5bfc8398f1dc
Revises: 4ee35b5568b6
Create Date: 2026-09-04 21:32:24.855922
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '5bfc8398f1dc'
down_revision: str | None = '4ee35b5568b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_locus__search_text_trigram', 'locus', ['search_text'], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locus__search_text_trigram', table_name='locus', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    # ### end Alembic commands ###
