"""index the foreign keys a re-ingest deletes through

Revision ID: 128186813705
Revises: 421c2d1737d7
Create Date: 2026-09-04 21:14:11.066473
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '128186813705'
down_revision: str | None = '421c2d1737d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_locus_membership__pangenome_id__genome_id'), table_name='gene_locus_membership')
    op.create_index('ix_gene_locus_membership__genome_id__pangenome_id', 'gene_locus_membership', ['genome_id', 'pangenome_id'], unique=False)
    op.create_index('ix_gene_locus_membership__locus_arrangement_id', 'gene_locus_membership', ['locus_arrangement_id'], unique=False)
    op.create_index('ix_locus__medoid_genome_id', 'locus', ['medoid_genome_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locus__medoid_genome_id', table_name='locus')
    op.drop_index('ix_gene_locus_membership__locus_arrangement_id', table_name='gene_locus_membership')
    op.drop_index('ix_gene_locus_membership__genome_id__pangenome_id', table_name='gene_locus_membership')
    op.create_index(op.f('ix_gene_locus_membership__pangenome_id__genome_id'), 'gene_locus_membership', ['pangenome_id', 'genome_id'], unique=False)
    # ### end Alembic commands ###
