"""the initial schema: genomes, collections, nuna models, pangenomes, loci

Revision ID: 167f47ef6e68
Revises: 
Create Date: 2026-09-04 16:23:01.073108
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '167f47ef6e68'
down_revision: str | None = None
branch_labels = None
depends_on = None


#: ⛔ Every ENUM type this migration creates. Alembic's autogenerated `downgrade` drops the TABLES
#: but NOT the types they used, so `downgrade base` leaves all of these orphaned in the schema and
#: the next `upgrade head` dies on `CREATE TYPE ... already exists`. Measured, not feared: eleven
#: types survived a downgrade here. A migration that cannot be reversed and re-applied is not
#: reversible, so they are dropped explicitly.
ENUM_TYPE_NAMES = (
    "annotationkind",
    "embeddingrepresentation",
    "evaluationkind",
    "exclusivityform",
    "exclusivityformsource",
    "gateverdict",
    "geneontologyagreementverdict",
    "prevalenceband",
    "rhorule",
    "rosterlineage",
    "sampleidentifierkind",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nuna_model',
    sa.Column('nuna_model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('dedup_identity', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('dedup_coverage', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('knn_k', sa.Integer(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('exclusivity_form', sa.Enum('EXCLUSION', 'DAMPED_EXCLUSION', 'NONE', name='exclusivityform'), nullable=False),
    sa.Column('merge_algorithm', sa.String(length=128), nullable=True),
    sa.Column('graph_construction', sa.String(length=128), nullable=True),
    sa.Column('step_count', sa.SmallInteger(), nullable=True),
    sa.Column('registry_source_git_sha', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('nuna_model_id', name=op.f('pk_nuna_model')),
    sa.UniqueConstraint('model_key', name=op.f('uq_nuna_model__model_key'))
    )
    op.create_table('pathogen_species',
    sa.Column('pathogen_species_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('species_key', sa.String(length=32), nullable=False),
    sa.Column('scientific_name', sa.String(length=128), nullable=False),
    sa.Column('ncbi_taxonomy_id', sa.Integer(), nullable=True),
    sa.Column('published_pangenome_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['published_pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_pathogen_species__published_pangenome_id__pangenome'), initially='DEFERRED', deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('pathogen_species_id', name=op.f('pk_pathogen_species')),
    sa.UniqueConstraint('species_key', name=op.f('uq_pathogen_species__species_key'))
    )
    op.create_table('genome',
    sa.Column('genome_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pathogen_species_id', sa.SmallInteger(), nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('sample_id_kind', sa.Enum('BIOSAMPLE', 'ASSEMBLY_STEM', name='sampleidentifierkind'), nullable=False),
    sa.Column('bare_accession', sa.String(length=128), nullable=True),
    sa.Column('bakrep_dataset_id', sa.String(length=64), nullable=True),
    sa.Column('sublineage', sa.String(length=64), nullable=True),
    sa.Column('lincode', sa.String(length=64), nullable=True),
    sa.Column('phylogroup', sa.String(length=64), nullable=True),
    sa.Column('is_kpsc_final_list', sa.Boolean(), nullable=True),
    sa.Column('is_complete_assembly', sa.Boolean(), nullable=True),
    sa.Column('is_hybrid_assembly', sa.Boolean(), nullable=True),
    sa.Column('contig_count_with_coding_sequence', sa.Integer(), nullable=True),
    sa.Column('total_base_count', sa.BigInteger(), nullable=True),
    sa.Column('coding_gene_count', sa.Integer(), nullable=True),
    sa.Column('strand_is_observed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pathogen_species_id'], ['pathogen_species.pathogen_species_id'], name=op.f('fk_genome__pathogen_species_id__pathogen_species')),
    sa.PrimaryKeyConstraint('genome_id', name=op.f('pk_genome')),
    sa.UniqueConstraint('sample_id', name=op.f('uq_genome__sample_id'))
    )
    op.create_index('ix_genome__bare_accession', 'genome', ['bare_accession'], unique=False)
    op.create_table('genome_collection',
    sa.Column('genome_collection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pathogen_species_id', sa.SmallInteger(), nullable=False),
    sa.Column('collection_key', sa.String(length=64), nullable=False),
    sa.Column('roster_lineage', sa.Enum('PROBE_BIOSAMPLE', 'KLEBSIELLA_METADATA_V2', name='rosterlineage'), nullable=False),
    sa.Column('genome_count', sa.Integer(), nullable=False),
    sa.Column('roster_source_path', sa.String(length=512), nullable=True),
    sa.Column('roster_source_sha256', sa.String(length=64), nullable=True),
    sa.Column('parent_genome_collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_genome_collection_id'], ['genome_collection.genome_collection_id'], name=op.f('fk_genome_collection__parent_genome_collection_id__genome_collection')),
    sa.ForeignKeyConstraint(['pathogen_species_id'], ['pathogen_species.pathogen_species_id'], name=op.f('fk_genome_collection__pathogen_species_id__pathogen_species')),
    sa.PrimaryKeyConstraint('genome_collection_id', name=op.f('pk_genome_collection')),
    sa.UniqueConstraint('pathogen_species_id', 'collection_key', name=op.f('uq_genome_collection__pathogen_species_id_collection_key'))
    )
    op.create_table('nuna_model_step',
    sa.Column('nuna_model_step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nuna_model_id', sa.Integer(), nullable=False),
    sa.Column('step_ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('step_name', sa.String(length=32), nullable=False),
    sa.Column('representation', sa.Enum('ESM', 'BACFORMER', name='embeddingrepresentation'), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('rho_rule', sa.Enum('OFF', 'CEILING', 'PAIRWISE_MAX', name='rhorule'), nullable=True),
    sa.Column('rho_ceiling', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rho_exit', sa.Boolean(), nullable=True),
    sa.Column('rho_continue', sa.String(length=16), nullable=True),
    sa.Column('node_mode', sa.String(length=32), nullable=True),
    sa.Column('uses_exclusivity', sa.Boolean(), nullable=False),
    sa.Column('edge_weight_expression', sa.String(length=64), nullable=True),
    sa.Column('node_sizes', sa.String(length=32), nullable=True),
    sa.Column('stage_name', sa.String(length=128), nullable=True),
    sa.Column('stage_detail', sa.Text(), nullable=True),
    sa.Column('provenance_source', sa.Enum('RUN_MANIFEST', 'RUN_ID_TOKEN', 'MODEL_REGISTRY', name='exclusivityformsource'), nullable=True),
    sa.ForeignKeyConstraint(['nuna_model_id'], ['nuna_model.nuna_model_id'], name=op.f('fk_nuna_model_step__nuna_model_id__nuna_model'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nuna_model_step_id', name=op.f('pk_nuna_model_step')),
    sa.UniqueConstraint('nuna_model_id', 'step_ordinal', name=op.f('uq_nuna_model_step__nuna_model_id_step_ordinal'))
    )
    op.create_table('gene',
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.Column('flat_index', sa.Integer(), nullable=False),
    sa.Column('pathogen_species_id', sa.SmallInteger(), nullable=False),
    sa.Column('contig_index', sa.SmallInteger(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=False),
    sa.Column('length_nt', sa.Integer(), nullable=False),
    sa.Column('strand', sa.String(length=1), nullable=False),
    sa.Column('strand_is_observed', sa.Boolean(), nullable=False),
    sa.Column('gff_phase', sa.SmallInteger(), nullable=False),
    sa.Column('is_five_prime_partial', sa.Boolean(), nullable=False),
    sa.Column('gc_percent', sa.Float(), nullable=True),
    sa.Column('protein_length_aa', sa.Integer(), nullable=True),
    sa.Column('bakta_gene_symbol', sa.String(length=128), nullable=True),
    sa.Column('bakta_product', sa.Text(), nullable=True),
    sa.Column('locus_tag', sa.String(length=64), nullable=True),
    sa.CheckConstraint("gc_percent IS NULL OR gc_percent <> 'NaN'::double precision", name=op.f('ck_gene__gc_percent_is_not_nan')),
    sa.CheckConstraint("strand IN ('+', '-')", name=op.f('ck_gene__strand_is_plus_or_minus')),
    sa.CheckConstraint('start_position >= 1 AND end_position >= start_position', name=op.f('ck_gene__span_is_forward')),
    sa.ForeignKeyConstraint(['genome_id'], ['genome.genome_id'], name=op.f('fk_gene__genome_id__genome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genome_id', 'flat_index', name=op.f('pk_gene'))
    )
    op.create_index('ix_gene__genome_id', 'gene', ['genome_id'], unique=False, postgresql_using='brin')
    op.create_index('ix_gene__genome_id__contig_index__start_position', 'gene', ['genome_id', 'contig_index', 'start_position'], unique=False)
    op.create_table('gene_functional_annotation',
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.Column('flat_index', sa.Integer(), nullable=False),
    sa.Column('uniref50_accession', sa.String(length=64), nullable=True),
    sa.Column('kegg_orthology_id', sa.String(length=32), nullable=True),
    sa.Column('cog_id', sa.String(length=32), nullable=True),
    sa.Column('cog_category', sa.String(length=16), nullable=True),
    sa.Column('ec_number', sa.String(length=32), nullable=True),
    sa.Column('gene_ontology_terms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['genome_id'], ['genome.genome_id'], name=op.f('fk_gene_functional_annotation__genome_id__genome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genome_id', 'flat_index', name=op.f('pk_gene_functional_annotation'))
    )
    op.create_index('ix_gene_functional_annotation__cog_id', 'gene_functional_annotation', ['cog_id'], unique=False)
    op.create_index('ix_gene_functional_annotation__uniref50_accession', 'gene_functional_annotation', ['uniref50_accession'], unique=False)
    op.create_table('genome_assembly',
    sa.Column('genome_assembly_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.Column('assembly_accession', sa.String(length=64), nullable=True),
    sa.Column('assembly_source', sa.String(length=32), nullable=True),
    sa.Column('assembly_file_path', sa.String(length=512), nullable=True),
    sa.Column('annotation_file_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['genome_id'], ['genome.genome_id'], name=op.f('fk_genome_assembly__genome_id__genome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genome_assembly_id', name=op.f('pk_genome_assembly')),
    sa.UniqueConstraint('genome_id', 'assembly_accession', name=op.f('uq_genome_assembly__genome_id_assembly_accession'))
    )
    op.create_table('genome_collection_build_report',
    sa.Column('genome_collection_id', sa.Integer(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=True),
    sa.Column('matched_exact_key_count', sa.Integer(), nullable=True),
    sa.Column('matched_bare_accession_count', sa.Integer(), nullable=True),
    sa.Column('not_in_metadata_count', sa.Integer(), nullable=True),
    sa.Column('no_usable_file_pair_count', sa.Integer(), nullable=True),
    sa.Column('path_present_file_absent_count', sa.Integer(), nullable=True),
    sa.Column('no_embedding_count', sa.Integer(), nullable=True),
    sa.Column('roster_count', sa.Integer(), nullable=True),
    sa.Column('coverage_meta_parquet', sa.Integer(), nullable=True),
    sa.Column('coverage_esm_embedding', sa.Integer(), nullable=True),
    sa.Column('coverage_bacformer_embedding', sa.Integer(), nullable=True),
    sa.Column('not_in_metadata_examples', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['genome_collection_id'], ['genome_collection.genome_collection_id'], name=op.f('fk_genome_collection_build_report__genome_collection_id__genome_collection'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genome_collection_id', name=op.f('pk_genome_collection_build_report'))
    )
    op.create_table('genome_collection_membership',
    sa.Column('genome_collection_id', sa.Integer(), nullable=False),
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.Column('collection_genome_ordinal', sa.Integer(), nullable=False),
    sa.Column('is_anchor', sa.Boolean(), nullable=False),
    sa.Column('assembly_file_path', sa.String(length=512), nullable=True),
    sa.Column('annotation_file_path', sa.String(length=512), nullable=True),
    sa.Column('file_path_source', sa.String(length=16), nullable=True),
    sa.Column('requested_sample_id', sa.String(length=128), nullable=True),
    sa.Column('matched_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['genome_collection_id'], ['genome_collection.genome_collection_id'], name=op.f('fk_genome_collection_membership__genome_collection_id__genome_collection'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genome_id'], ['genome.genome_id'], name=op.f('fk_genome_collection_membership__genome_id__genome')),
    sa.PrimaryKeyConstraint('genome_collection_id', 'genome_id', name=op.f('pk_genome_collection_membership')),
    sa.UniqueConstraint('genome_collection_id', 'collection_genome_ordinal', name=op.f('uq_genome_collection_membership__genome_collection_id_collection_genome_ordinal'))
    )
    op.create_index('ix_genome_collection_membership__genome_id', 'genome_collection_membership', ['genome_id'], unique=False)
    op.create_table('genome_contig',
    sa.Column('genome_contig_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.Column('seqid', sa.String(length=128), nullable=False),
    sa.Column('contig_index', sa.SmallInteger(), nullable=False),
    sa.Column('contig_name', sa.String(length=128), nullable=False),
    sa.Column('length_bases', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genome_id'], ['genome.genome_id'], name=op.f('fk_genome_contig__genome_id__genome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genome_contig_id', name=op.f('pk_genome_contig')),
    sa.UniqueConstraint('genome_id', 'seqid', name=op.f('uq_genome_contig__genome_id_seqid'))
    )
    op.create_index('ix_genome_contig__genome_id__contig_index', 'genome_contig', ['genome_id', 'contig_index'], unique=False)
    op.create_table('genome_noncoding_feature',
    sa.Column('genome_noncoding_feature_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.Column('contig_index', sa.SmallInteger(), nullable=False),
    sa.Column('noncoding_feature_index', sa.Integer(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=False),
    sa.Column('strand', sa.String(length=1), nullable=True),
    sa.Column('feature_type', sa.String(length=64), nullable=False),
    sa.Column('feature_gene', sa.String(length=128), nullable=True),
    sa.Column('feature_product', sa.Text(), nullable=True),
    sa.Column('overlaps_coding_sequence', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['genome_id'], ['genome.genome_id'], name=op.f('fk_genome_noncoding_feature__genome_id__genome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genome_noncoding_feature_id', name=op.f('pk_genome_noncoding_feature')),
    sa.UniqueConstraint('genome_id', 'contig_index', 'noncoding_feature_index', name=op.f('uq_genome_noncoding_feature__genome_id_contig_index_noncoding_feature_index'))
    )
    op.create_index('ix_genome_noncoding_feature__genome_id__contig_index', 'genome_noncoding_feature', ['genome_id', 'contig_index'], unique=False)
    op.create_table('pangenome',
    sa.Column('pangenome_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=256), nullable=False),
    sa.Column('ingest_generation', sa.Integer(), nullable=False),
    sa.Column('pathogen_species_id', sa.SmallInteger(), nullable=False),
    sa.Column('genome_collection_id', sa.Integer(), nullable=False),
    sa.Column('nuna_model_id', sa.Integer(), nullable=True),
    sa.Column('exclusivity_form', sa.Enum('EXCLUSION', 'DAMPED_EXCLUSION', 'NONE', name='exclusivityform'), nullable=False),
    sa.Column('exclusivity_form_source', sa.Enum('RUN_MANIFEST', 'RUN_ID_TOKEN', 'MODEL_REGISTRY', name='exclusivityformsource'), nullable=False),
    sa.Column('run_id_exclusivity_token', sa.String(length=16), nullable=True),
    sa.Column('genome_count', sa.Integer(), nullable=False),
    sa.Column('gene_count', sa.BigInteger(), nullable=False),
    sa.Column('locus_count', sa.Integer(), nullable=False),
    sa.Column('assignment_file_path', sa.String(length=512), nullable=True),
    sa.Column('assignment_sha256', sa.String(length=64), nullable=True),
    sa.Column('run_manifest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chain_manifest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('omitted_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('built_at', sa.String(length=32), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.CheckConstraint("run_id_exclusivity_token IS NULL OR (run_id_exclusivity_token = '-exclLOGP' AND exclusivity_form = 'EXCLUSION') OR (run_id_exclusivity_token = '-excl' AND exclusivity_form = 'DAMPED_EXCLUSION')", name=op.f('ck_pangenome__exclusivity_token_agrees')),
    sa.ForeignKeyConstraint(['genome_collection_id'], ['genome_collection.genome_collection_id'], name=op.f('fk_pangenome__genome_collection_id__genome_collection')),
    sa.ForeignKeyConstraint(['nuna_model_id'], ['nuna_model.nuna_model_id'], name=op.f('fk_pangenome__nuna_model_id__nuna_model')),
    sa.ForeignKeyConstraint(['pathogen_species_id'], ['pathogen_species.pathogen_species_id'], name=op.f('fk_pangenome__pathogen_species_id__pathogen_species')),
    sa.PrimaryKeyConstraint('pangenome_id', name=op.f('pk_pangenome')),
    sa.UniqueConstraint('run_id', 'ingest_generation', name=op.f('uq_pangenome__run_id_ingest_generation'))
    )
    op.create_table('locus',
    sa.Column('locus_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('pathogen_species_id', sa.SmallInteger(), nullable=False),
    sa.Column('node_label', sa.String(length=64), nullable=False),
    sa.Column('catalogue_ordinal', sa.Integer(), nullable=False),
    sa.Column('member_gene_count', sa.Integer(), nullable=False),
    sa.Column('member_genome_count', sa.Integer(), nullable=False),
    sa.Column('prevalence_band', sa.Enum('CORE', 'SOFT_CORE', 'SHELL', 'CLOUD', 'RARE', name='prevalenceband'), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('display_name_source', sa.String(length=32), nullable=False),
    sa.Column('display_name_source_accession', sa.String(length=64), nullable=True),
    sa.Column('best_product', sa.Text(), nullable=True),
    sa.Column('bakta_gene_symbol', sa.String(length=128), nullable=True),
    sa.Column('named_member_count', sa.Integer(), nullable=False),
    sa.Column('uniref50_family_count', sa.Integer(), nullable=True),
    sa.Column('uniref50_major_family_count', sa.Integer(), nullable=True),
    sa.Column('uniref50_labelled_member_count', sa.Integer(), nullable=True),
    sa.Column('uniref50_impurity', sa.Float(), nullable=True),
    sa.Column('uniref50_coverage', sa.Float(), nullable=True),
    sa.Column('pfam_annotated_member_count', sa.Integer(), nullable=True),
    sa.Column('pfam_architecture_count', sa.Integer(), nullable=True),
    sa.Column('pfam_concordance_class', sa.String(length=32), nullable=True),
    sa.Column('syntenic_a5', sa.Float(), nullable=True),
    sa.Column('collapse_tier', sa.String(length=64), nullable=True),
    sa.Column('collapse_bucket', sa.String(length=64), nullable=True),
    sa.Column('resolved_threshold', sa.Float(), nullable=True),
    sa.Column('seqid_coverage', sa.Float(), nullable=True),
    sa.Column('esm_within_medoid_distance', sa.Float(), nullable=True),
    sa.Column('esm_nearest_medoid_distance', sa.Float(), nullable=True),
    sa.Column('bacformer_within_medoid_distance', sa.Float(), nullable=True),
    sa.Column('bacformer_nearest_medoid_distance', sa.Float(), nullable=True),
    sa.Column('embed_within_over_nearest', sa.Float(), nullable=True),
    sa.Column('medoid_genome_id', sa.Integer(), nullable=True),
    sa.Column('medoid_flat_index', sa.Integer(), nullable=True),
    sa.Column('separation_percentile_esm', sa.Float(), nullable=True),
    sa.Column('separation_percentile_bacformer', sa.Float(), nullable=True),
    sa.Column('cog_annotated_member_count', sa.Integer(), nullable=True),
    sa.Column('cog_distinct_id_count', sa.Integer(), nullable=True),
    sa.Column('modal_cog_category', sa.String(length=16), nullable=True),
    sa.Column('ec_annotated_member_count', sa.Integer(), nullable=True),
    sa.Column('kegg_annotated_member_count', sa.Integer(), nullable=True),
    sa.Column('go_annotated_member_count_molecular_function', sa.Integer(), nullable=True),
    sa.Column('go_annotated_member_count_biological_process', sa.Integer(), nullable=True),
    sa.Column('go_annotated_member_count_cellular_component', sa.Integer(), nullable=True),
    sa.Column('go_verdict_molecular_function', sa.Enum('NO_COVERAGE', 'SINGLE', 'SAME_DOMAINS', 'NESTED', 'OVERLAPPING', 'DISJOINT', name='geneontologyagreementverdict'), nullable=True),
    sa.Column('go_verdict_biological_process', sa.Enum('NO_COVERAGE', 'SINGLE', 'SAME_DOMAINS', 'NESTED', 'OVERLAPPING', 'DISJOINT', name='geneontologyagreementverdict'), nullable=True),
    sa.Column('go_verdict_cellular_component', sa.Enum('NO_COVERAGE', 'SINGLE', 'SAME_DOMAINS', 'NESTED', 'OVERLAPPING', 'DISJOINT', name='geneontologyagreementverdict'), nullable=True),
    sa.Column('median_gene_length_nt', sa.Integer(), nullable=True),
    sa.Column('gene_length_interquartile_range_nt', sa.Integer(), nullable=True),
    sa.Column('context_observed_member_counts', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('total_arrangement_count', sa.Integer(), nullable=False),
    sa.Column('interest_score', sa.Float(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.CheckConstraint("bacformer_nearest_medoid_distance IS NULL OR bacformer_nearest_medoid_distance <> 'NaN'::double precision", name=op.f('ck_locus__bacformer_nearest_medoid_distance_is_not_nan')),
    sa.CheckConstraint("bacformer_within_medoid_distance IS NULL OR bacformer_within_medoid_distance <> 'NaN'::double precision", name=op.f('ck_locus__bacformer_within_medoid_distance_is_not_nan')),
    sa.CheckConstraint("embed_within_over_nearest IS NULL OR embed_within_over_nearest <> 'NaN'::double precision", name=op.f('ck_locus__embed_within_over_nearest_is_not_nan')),
    sa.CheckConstraint("esm_nearest_medoid_distance IS NULL OR esm_nearest_medoid_distance <> 'NaN'::double precision", name=op.f('ck_locus__esm_nearest_medoid_distance_is_not_nan')),
    sa.CheckConstraint("esm_within_medoid_distance IS NULL OR esm_within_medoid_distance <> 'NaN'::double precision", name=op.f('ck_locus__esm_within_medoid_distance_is_not_nan')),
    sa.CheckConstraint("interest_score IS NULL OR interest_score <> 'NaN'::double precision", name=op.f('ck_locus__interest_score_is_not_nan')),
    sa.CheckConstraint("resolved_threshold IS NULL OR resolved_threshold <> 'NaN'::double precision", name=op.f('ck_locus__resolved_threshold_is_not_nan')),
    sa.CheckConstraint("separation_percentile_bacformer IS NULL OR separation_percentile_bacformer <> 'NaN'::double precision", name=op.f('ck_locus__separation_percentile_bacformer_is_not_nan')),
    sa.CheckConstraint("separation_percentile_esm IS NULL OR separation_percentile_esm <> 'NaN'::double precision", name=op.f('ck_locus__separation_percentile_esm_is_not_nan')),
    sa.CheckConstraint("seqid_coverage IS NULL OR seqid_coverage <> 'NaN'::double precision", name=op.f('ck_locus__seqid_coverage_is_not_nan')),
    sa.CheckConstraint("syntenic_a5 IS NULL OR syntenic_a5 <> 'NaN'::double precision", name=op.f('ck_locus__syntenic_a5_is_not_nan')),
    sa.CheckConstraint("uniref50_coverage IS NULL OR uniref50_coverage <> 'NaN'::double precision", name=op.f('ck_locus__uniref50_coverage_is_not_nan')),
    sa.CheckConstraint("uniref50_impurity IS NULL OR uniref50_impurity <> 'NaN'::double precision", name=op.f('ck_locus__uniref50_impurity_is_not_nan')),
    sa.ForeignKeyConstraint(['medoid_genome_id'], ['genome.genome_id'], name=op.f('fk_locus__medoid_genome_id__genome')),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_locus__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pathogen_species_id'], ['pathogen_species.pathogen_species_id'], name=op.f('fk_locus__pathogen_species_id__pathogen_species')),
    sa.PrimaryKeyConstraint('locus_id', name=op.f('pk_locus')),
    sa.UniqueConstraint('pangenome_id', 'catalogue_ordinal', name=op.f('uq_locus__pangenome_id_catalogue_ordinal')),
    sa.UniqueConstraint('pangenome_id', 'node_label', name=op.f('uq_locus__pangenome_id_node_label'))
    )
    op.create_index('ix_locus__pangenome_id__interest_score', 'locus', ['pangenome_id', 'interest_score'], unique=False)
    op.create_index('ix_locus__pangenome_id__member_genome_count', 'locus', ['pangenome_id', 'member_genome_count'], unique=False)
    op.create_index('ix_locus__pangenome_id__prevalence_band', 'locus', ['pangenome_id', 'prevalence_band'], unique=False)
    op.create_table('locus_map_projection',
    sa.Column('locus_map_projection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('representation', sa.Enum('ESM', 'BACFORMER', name='embeddingrepresentation'), nullable=False),
    sa.Column('projection_method', sa.String(length=64), nullable=True),
    sa.Column('requested_metric', sa.String(length=32), nullable=True),
    sa.Column('neighbour_count', sa.SmallInteger(), nullable=False),
    sa.Column('scale_centre_x', sa.Float(), nullable=True),
    sa.Column('scale_centre_y', sa.Float(), nullable=True),
    sa.Column('scale_span', sa.Float(), nullable=True),
    sa.Column('scale_unit', sa.Integer(), nullable=True),
    sa.Column('extent_min_x', sa.Integer(), nullable=True),
    sa.Column('extent_min_y', sa.Integer(), nullable=True),
    sa.Column('extent_max_x', sa.Integer(), nullable=True),
    sa.Column('extent_max_y', sa.Integer(), nullable=True),
    sa.Column('cos6_pair_order_version', sa.SmallInteger(), nullable=False),
    sa.Column('cosine_scale_factor', sa.Integer(), nullable=False),
    sa.Column('source_csv_path', sa.String(length=512), nullable=True),
    sa.Column('null_bin_lower_edge', sa.Float(), nullable=True),
    sa.Column('null_bin_width', sa.Float(), nullable=True),
    sa.Column('null_bin_counts', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('null_mean_cosine', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_locus_map_projection__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_map_projection_id', name=op.f('pk_locus_map_projection')),
    sa.UniqueConstraint('pangenome_id', 'representation', name=op.f('uq_locus_map_projection__pangenome_id_representation'))
    )
    op.create_table('pangenome_evaluation',
    sa.Column('pangenome_evaluation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_kind', sa.Enum('COPY_STRUCTURE_GATE', 'ACCESSORY_AUDIT', 'MERGE_EVIDENCE', name='evaluationkind'), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('verdict', sa.Enum('PASS', 'FAIL', 'INCOMPLETE', name='gateverdict'), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source_artifact_path', sa.String(length=512), nullable=True),
    sa.CheckConstraint("numeric_value IS NULL OR numeric_value <> 'NaN'::double precision", name=op.f('ck_pangenome_evaluation__numeric_value_is_not_nan')),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_pangenome_evaluation__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pangenome_evaluation_id', name=op.f('pk_pangenome_evaluation')),
    sa.UniqueConstraint('pangenome_id', 'evaluation_kind', 'metric_name', name=op.f('uq_pangenome_evaluation__pangenome_id_evaluation_kind_metric_name'))
    )
    op.create_index('ix_pangenome_evaluation__kind_verdict', 'pangenome_evaluation', ['evaluation_kind', 'verdict'], unique=False)
    op.create_table('pangenome_input_edge',
    sa.Column('pangenome_input_edge_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('child_pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_run_id', sa.String(length=256), nullable=False),
    sa.Column('parent_pangenome_id', sa.BigInteger(), nullable=True),
    sa.Column('input_key', sa.String(length=32), nullable=False),
    sa.Column('depth', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("input_key IN ('precluster_assign', 'atoms_assign', 'step2_assign')", name=op.f('ck_pangenome_input_edge__input_key_is_known')),
    sa.ForeignKeyConstraint(['child_pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_pangenome_input_edge__child_pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_pangenome_input_edge__parent_pangenome_id__pangenome')),
    sa.PrimaryKeyConstraint('pangenome_input_edge_id', name=op.f('pk_pangenome_input_edge')),
    sa.UniqueConstraint('child_pangenome_id', 'input_key', 'parent_run_id', name=op.f('uq_pangenome_input_edge__child_pangenome_id_input_key_parent_run_id'))
    )
    op.create_table('pangenome_step',
    sa.Column('pangenome_step_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('step_ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('step_name', sa.String(length=32), nullable=False),
    sa.Column('representation', sa.Enum('ESM', 'BACFORMER', name='embeddingrepresentation'), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('rho_rule', sa.Enum('OFF', 'CEILING', 'PAIRWISE_MAX', name='rhorule'), nullable=True),
    sa.Column('rho_ceiling', sa.Float(), nullable=True),
    sa.Column('node_mode', sa.String(length=32), nullable=True),
    sa.Column('uses_exclusivity', sa.Boolean(), nullable=True),
    sa.Column('step_assignment_path', sa.String(length=512), nullable=True),
    sa.Column('gene_count', sa.BigInteger(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('wall_seconds', sa.Float(), nullable=True),
    sa.Column('peak_rss_gigabytes', sa.Float(), nullable=True),
    sa.Column('stage_name', sa.String(length=128), nullable=True),
    sa.Column('stage_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_pangenome_step__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pangenome_step_id', name=op.f('pk_pangenome_step')),
    sa.UniqueConstraint('pangenome_id', 'step_ordinal', name=op.f('uq_pangenome_step__pangenome_id_step_ordinal'))
    )
    op.create_table('intergenic_gap',
    sa.Column('intergenic_gap_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('flanking_locus_id_low', sa.BigInteger(), nullable=False),
    sa.Column('flanking_locus_id_high', sa.BigInteger(), nullable=False),
    sa.Column('observed_genome_count', sa.Integer(), nullable=False),
    sa.Column('median_signed_length_nt', sa.Integer(), nullable=False),
    sa.Column('quartile1_signed_length_nt', sa.Integer(), nullable=True),
    sa.Column('quartile3_signed_length_nt', sa.Integer(), nullable=True),
    sa.Column('minimum_signed_length_nt', sa.Integer(), nullable=True),
    sa.Column('maximum_signed_length_nt', sa.Integer(), nullable=True),
    sa.Column('length_variance_score', sa.Float(), nullable=True),
    sa.Column('modal_length_nt', sa.Integer(), nullable=True),
    sa.Column('distinct_named_feature_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("length_variance_score IS NULL OR length_variance_score <> 'NaN'::double precision", name=op.f('ck_intergenic_gap__length_variance_score_is_not_nan')),
    sa.CheckConstraint('flanking_locus_id_low <= flanking_locus_id_high', name=op.f('ck_intergenic_gap__flanking_pair_is_sorted')),
    sa.ForeignKeyConstraint(['flanking_locus_id_high'], ['locus.locus_id'], name=op.f('fk_intergenic_gap__flanking_locus_id_high__locus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flanking_locus_id_low'], ['locus.locus_id'], name=op.f('fk_intergenic_gap__flanking_locus_id_low__locus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_intergenic_gap__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intergenic_gap_id', name=op.f('pk_intergenic_gap')),
    sa.UniqueConstraint('pangenome_id', 'flanking_locus_id_low', 'flanking_locus_id_high', name=op.f('uq_intergenic_gap__pangenome_id_flanking_locus_id_low_flanking_locus_id_high'))
    )
    op.create_index('ix_intergenic_gap__flanking_locus_id_high', 'intergenic_gap', ['flanking_locus_id_high'], unique=False)
    op.create_index('ix_intergenic_gap__flanking_locus_id_low', 'intergenic_gap', ['flanking_locus_id_low'], unique=False)
    op.create_table('locus_annotation_entry',
    sa.Column('locus_annotation_entry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locus_id', sa.BigInteger(), nullable=False),
    sa.Column('annotation_kind', sa.Enum('GENE_SYMBOL', 'PROTEIN_PRODUCT', 'PFAM_ARCHITECTURE', 'COG_ORTHOGROUP', 'GENE_ONTOLOGY_SLIM', 'EC_NUMBER', 'KEGG_ORTHOLOGY', name='annotationkind'), nullable=False),
    sa.Column('rank_within_locus', sa.SmallInteger(), nullable=False),
    sa.Column('term_value', sa.String(length=256), nullable=False),
    sa.Column('term_name', sa.Text(), nullable=True),
    sa.Column('member_gene_count', sa.Integer(), nullable=False),
    sa.Column('gene_ontology_namespace', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_locus_annotation_entry__locus_id__locus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_annotation_entry_id', name=op.f('pk_locus_annotation_entry')),
    sa.UniqueConstraint('locus_id', 'annotation_kind', 'rank_within_locus', name=op.f('uq_locus_annotation_entry__locus_id_annotation_kind_rank_within_locus'))
    )
    op.create_index('ix_locus_annotation_entry__annotation_kind__term_value', 'locus_annotation_entry', ['annotation_kind', 'term_value'], unique=False)
    op.create_index('ix_locus_annotation_entry__locus_id__annotation_kind', 'locus_annotation_entry', ['locus_id', 'annotation_kind'], unique=False)
    op.create_table('locus_arrangement',
    sa.Column('locus_arrangement_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locus_id', sa.BigInteger(), nullable=False),
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_within_locus', sa.Integer(), nullable=False),
    sa.Column('member_gene_count', sa.Integer(), nullable=False),
    sa.Column('member_genome_count', sa.Integer(), nullable=False),
    sa.Column('is_recorded_reverse_complement', sa.Boolean(), nullable=False),
    sa.Column('neighbour_slot_codes', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('member_genome_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_locus_arrangement__locus_id__locus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_arrangement_id', name=op.f('pk_locus_arrangement')),
    sa.UniqueConstraint('locus_id', 'rank_within_locus', name=op.f('uq_locus_arrangement__locus_id_rank_within_locus'))
    )
    op.create_index('ix_locus_arrangement__locus_id', 'locus_arrangement', ['locus_id'], unique=False)
    op.create_index('ix_locus_arrangement__member_genome_ids', 'locus_arrangement', ['member_genome_ids'], unique=False, postgresql_using='gin')
    op.create_table('locus_embedding_geometry',
    sa.Column('locus_embedding_geometry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locus_id', sa.BigInteger(), nullable=False),
    sa.Column('representation', sa.Enum('ESM', 'BACFORMER', name='embeddingrepresentation'), nullable=False),
    sa.Column('map_x', sa.SmallInteger(), nullable=False),
    sa.Column('map_y', sa.SmallInteger(), nullable=False),
    sa.Column('nearest_locus_ordinals', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('pairwise_cosine_scaled', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_locus_embedding_geometry__locus_id__locus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_embedding_geometry_id', name=op.f('pk_locus_embedding_geometry')),
    sa.UniqueConstraint('locus_id', 'representation', name=op.f('uq_locus_embedding_geometry__locus_id_representation'))
    )
    op.create_table('locus_offset_occupant',
    sa.Column('locus_offset_occupant_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locus_id', sa.BigInteger(), nullable=False),
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('signed_offset', sa.SmallInteger(), nullable=False),
    sa.Column('rank_within_offset', sa.SmallInteger(), nullable=False),
    sa.Column('neighbour_locus_id', sa.BigInteger(), nullable=False),
    sa.Column('member_gene_count', sa.Integer(), nullable=False),
    sa.Column('same_strand_member_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('signed_offset BETWEEN -5 AND 5 AND signed_offset <> 0', name=op.f('ck_locus_offset_occupant__signed_offset_excludes_zero')),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_locus_offset_occupant__locus_id__locus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['neighbour_locus_id'], ['locus.locus_id'], name=op.f('fk_locus_offset_occupant__neighbour_locus_id__locus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_offset_occupant_id', name=op.f('pk_locus_offset_occupant')),
    sa.UniqueConstraint('locus_id', 'signed_offset', 'rank_within_offset', name=op.f('uq_locus_offset_occupant__locus_id_signed_offset_rank_within_offset'))
    )
    op.create_index('ix_locus_offset_occupant__locus_id__signed_offset', 'locus_offset_occupant', ['locus_id', 'signed_offset'], unique=False)
    op.create_index('ix_locus_offset_occupant__neighbour_locus_id', 'locus_offset_occupant', ['neighbour_locus_id'], unique=False)
    op.create_table('locus_uniref_family_crosstab',
    sa.Column('locus_uniref_family_crosstab_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locus_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_within_locus', sa.SmallInteger(), nullable=False),
    sa.Column('uniref50_accession', sa.String(length=64), nullable=False),
    sa.Column('member_gene_count', sa.Integer(), nullable=False),
    sa.Column('modal_bakta_product', sa.Text(), nullable=True),
    sa.Column('modal_pfam_architecture', sa.String(length=512), nullable=True),
    sa.Column('pfam_annotated_member_count', sa.Integer(), nullable=True),
    sa.Column('modal_bakta_gene_symbol', sa.String(length=128), nullable=True),
    sa.Column('distinct_real_symbol_count', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_locus_uniref_family_crosstab__locus_id__locus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_uniref_family_crosstab_id', name=op.f('pk_locus_uniref_family_crosstab')),
    sa.UniqueConstraint('locus_id', 'rank_within_locus', name=op.f('uq_locus_uniref_family_crosstab__locus_id_rank_within_locus'))
    )
    op.create_index('ix_locus_uniref_family_crosstab__uniref50_accession', 'locus_uniref_family_crosstab', ['uniref50_accession'], unique=False)
    op.create_table('gene_locus_membership',
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.Column('flat_index', sa.Integer(), nullable=False),
    sa.Column('locus_id', sa.BigInteger(), nullable=False),
    sa.Column('locus_arrangement_id', sa.BigInteger(), nullable=True),
    sa.Column('is_representative', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['genome_id'], ['genome.genome_id'], name=op.f('fk_gene_locus_membership__genome_id__genome'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locus_arrangement_id'], ['locus_arrangement.locus_arrangement_id'], name=op.f('fk_gene_locus_membership__locus_arrangement_id__locus_arrangement'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_gene_locus_membership__locus_id__locus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_gene_locus_membership__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pangenome_id', 'genome_id', 'flat_index', name=op.f('pk_gene_locus_membership'))
    )
    op.create_index('ix_gene_locus_membership__locus_id', 'gene_locus_membership', ['locus_id'], unique=False)
    op.create_index('ix_gene_locus_membership__locus_id__genome_id', 'gene_locus_membership', ['locus_id', 'genome_id'], unique=False)
    op.create_index('ix_gene_locus_membership__pangenome_id__genome_id', 'gene_locus_membership', ['pangenome_id', 'genome_id'], unique=False)
    op.create_table('intergenic_gap_feature',
    sa.Column('intergenic_gap_feature_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('intergenic_gap_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_within_gap', sa.SmallInteger(), nullable=False),
    sa.Column('feature_label', sa.String(length=256), nullable=False),
    sa.Column('feature_type', sa.String(length=64), nullable=False),
    sa.Column('observed_genome_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intergenic_gap_id'], ['intergenic_gap.intergenic_gap_id'], name=op.f('fk_intergenic_gap_feature__intergenic_gap_id__intergenic_gap'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intergenic_gap_feature_id', name=op.f('pk_intergenic_gap_feature')),
    sa.UniqueConstraint('intergenic_gap_id', 'rank_within_gap', name=op.f('uq_intergenic_gap_feature__intergenic_gap_id_rank_within_gap'))
    )
    # ⛔ The CIRCULAR foreign key, added here by hand because autogenerate omits it.
    # `pathogen_species.published_pangenome_id` references `pangenome`, and `pangenome` references
    # `pathogen_species` — so it can only be created after BOTH tables exist, via ALTER. Alembic
    # ordered the tables correctly and then dropped this edge on the floor; a drift probe
    # (autogenerate against the freshly-migrated database) is what surfaced it.
    # It is not cosmetic: this column is the publish-flip pointer, and without the constraint
    # nothing stops it naming a pangenome that does not exist.
    op.create_foreign_key(
        op.f('fk_pathogen_species__published_pangenome_id__pangenome'),
        'pathogen_species', 'pangenome', ['published_pangenome_id'], ['pangenome_id'],
        initially='DEFERRED', deferrable=True, use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop the circular FK first — the tables cannot be dropped while it stands.
    op.drop_constraint(
        op.f('fk_pathogen_species__published_pangenome_id__pangenome'),
        'pathogen_species', type_='foreignkey',
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intergenic_gap_feature')
    op.drop_index('ix_gene_locus_membership__pangenome_id__genome_id', table_name='gene_locus_membership')
    op.drop_index('ix_gene_locus_membership__locus_id__genome_id', table_name='gene_locus_membership')
    op.drop_index('ix_gene_locus_membership__locus_id', table_name='gene_locus_membership')
    op.drop_table('gene_locus_membership')
    op.drop_index('ix_locus_uniref_family_crosstab__uniref50_accession', table_name='locus_uniref_family_crosstab')
    op.drop_table('locus_uniref_family_crosstab')
    op.drop_index('ix_locus_offset_occupant__neighbour_locus_id', table_name='locus_offset_occupant')
    op.drop_index('ix_locus_offset_occupant__locus_id__signed_offset', table_name='locus_offset_occupant')
    op.drop_table('locus_offset_occupant')
    op.drop_table('locus_embedding_geometry')
    op.drop_index('ix_locus_arrangement__member_genome_ids', table_name='locus_arrangement', postgresql_using='gin')
    op.drop_index('ix_locus_arrangement__locus_id', table_name='locus_arrangement')
    op.drop_table('locus_arrangement')
    op.drop_index('ix_locus_annotation_entry__locus_id__annotation_kind', table_name='locus_annotation_entry')
    op.drop_index('ix_locus_annotation_entry__annotation_kind__term_value', table_name='locus_annotation_entry')
    op.drop_table('locus_annotation_entry')
    op.drop_index('ix_intergenic_gap__flanking_locus_id_low', table_name='intergenic_gap')
    op.drop_index('ix_intergenic_gap__flanking_locus_id_high', table_name='intergenic_gap')
    op.drop_table('intergenic_gap')
    op.drop_table('pangenome_step')
    op.drop_table('pangenome_input_edge')
    op.drop_index('ix_pangenome_evaluation__kind_verdict', table_name='pangenome_evaluation')
    op.drop_table('pangenome_evaluation')
    op.drop_table('locus_map_projection')
    op.drop_index('ix_locus__pangenome_id__prevalence_band', table_name='locus')
    op.drop_index('ix_locus__pangenome_id__member_genome_count', table_name='locus')
    op.drop_index('ix_locus__pangenome_id__interest_score', table_name='locus')
    op.drop_table('locus')
    op.drop_table('pangenome')
    op.drop_index('ix_genome_noncoding_feature__genome_id__contig_index', table_name='genome_noncoding_feature')
    op.drop_table('genome_noncoding_feature')
    op.drop_index('ix_genome_contig__genome_id__contig_index', table_name='genome_contig')
    op.drop_table('genome_contig')
    op.drop_index('ix_genome_collection_membership__genome_id', table_name='genome_collection_membership')
    op.drop_table('genome_collection_membership')
    op.drop_table('genome_collection_build_report')
    op.drop_table('genome_assembly')
    op.drop_index('ix_gene_functional_annotation__uniref50_accession', table_name='gene_functional_annotation')
    op.drop_index('ix_gene_functional_annotation__cog_id', table_name='gene_functional_annotation')
    op.drop_table('gene_functional_annotation')
    op.drop_index('ix_gene__genome_id__contig_index__start_position', table_name='gene')
    op.drop_index('ix_gene__genome_id', table_name='gene', postgresql_using='brin')
    op.drop_table('gene')
    op.drop_table('nuna_model_step')
    op.drop_table('genome_collection')
    op.drop_index('ix_genome__bare_accession', table_name='genome')
    op.drop_table('genome')
    op.drop_table('pathogen_species')
    op.drop_table('nuna_model')
    # Drop the enum types the tables above used — see ENUM_TYPE_NAMES.
    for type_name in ENUM_TYPE_NAMES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
    # ### end Alembic commands ###
