"""a locus can flank itself: tandem toxin-antitoxin repeats

Revision ID: 421c2d1737d7
Revises: 33366736bf35
Create Date: 2026-09-04 21:00:51.446187
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '421c2d1737d7'
down_revision: str | None = '33366736bf35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_intergenic_gap__flanking_pair_is_two_distinct_loci'), 'intergenic_gap', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_intergenic_gap__flanking_pair_is_two_distinct_loci'), 'intergenic_gap', 'flanking_locus_id_a <> flanking_locus_id_b')
    # ### end Alembic commands ###
