"""an audit metric name is compositional and must not be truncated

Revision ID: 4447f227b6e9
Revises: 5bfc8398f1dc
Create Date: 2026-09-04 21:46:49.002521
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '4447f227b6e9'
down_revision: str | None = '5bfc8398f1dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pangenome_evaluation', 'metric_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pangenome_evaluation', 'metric_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
