"""Set-to-set similarity replaces the medoid geometry — and the map goes with it

Revision ID: 858439e8fd7c
Revises: e2a5c81f4b73
Create Date: 2026-09-24

⛔ **One migration, because they were one construction.** `locus.{esm,bacformer}_{within,nearest}_medoid_
distance` measured a locus by reducing it to ONE member — the gene with the highest cosine to its centroid —
and then measuring that point. `locus_map_projection` + `locus_embedding_geometry` were a UMAP over those
same medoids, with each locus's ring drawn from `within_medoid_distance`; `locus_map_scatter_sprite` was
that map pre-rendered; the `null_*` columns were their baseline, sampled over random pairs of **medoids**.
Drop one and keep another and you have a picture of numbers that no longer exist.

What replaces them measures the whole **set**, or anchors on a **point**, and needs a grain the four columns
could not express — (locus, representation) — so it is a table rather than more columns:

  · `locus_similarity`              the eight numbers the card's three views show, per representation
  · `locus_nearest_locus`           the five nearest OTHER loci, ranked, each with its own similarity
  · `pangenome_similarity_baseline` the random GENE-pair floor, and the "of 12,104 loci" denominator

⚠ **Net table count is unchanged: three out, three in.** Do not read the count as evidence that nothing
moved — every row in all three new tables comes from a different artifact than the ones being dropped.

⛔ **This migration DESTROYS data and the downgrade cannot restore it.** The downgrade recreates the three
tables empty and the seven columns NULL, because the numbers came from CSV artifacts, not from anything in
this database. Rolling back means re-running the ingest against a `catalogue_map`/`null` run — which
`catalogue_map.py` still writes, deliberately, for exactly this reason.

⚠ `medoid_genome_id` and `medoid_flat_index` deliberately SURVIVE. They name the representative member,
which is an ordinary fact about a locus rather than a geometry, and the FK + its index go on being valid.

⚠ **Every new name is short enough that its constraint name does not TRUNCATE.** Postgres caps an
identifier at 63 characters and SQLAlchemy substitutes a 4-hex hash past that, so the database gets a name
nobody wrote — and autogenerate compares check constraints against the name that was *asked* for, so such a
table reports as drifted from its own migration forever. The first draft of this table did exactly that.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '858439e8fd7c'
down_revision: str | None = 'e2a5c81f4b73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pangenome_similarity_baseline',
    sa.Column('pangenome_similarity_baseline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pangenome_id', sa.BigInteger(), nullable=False),
    sa.Column('representation',
        # ⛔ `create_type=False`. Autogenerate emits `sa.Enum`, which tries CREATE TYPE — and the type
        # was created by the initial schema, so without this the migration dies on its FIRST table
        # with `DuplicateObject` and leaves nothing applied. Same flag, same reason, on the way down.
        postgresql.ENUM('ESM', 'BACFORMER', name='embeddingrepresentation', create_type=False),
        nullable=False),
    sa.Column('similarity_form', sa.String(length=16), nullable=False),
    sa.Column('floor_median', sa.Float(), nullable=True),
    sa.Column('floor_p25', sa.Float(), nullable=True),
    sa.Column('floor_p75', sa.Float(), nullable=True),
    sa.Column('floor_p99', sa.Float(), nullable=True),
    sa.Column('measurable_locus_count', sa.Integer(), nullable=True),
    sa.Column('neighbour_knn_k', sa.Integer(), nullable=True),
    sa.Column('nearest_locus_count', sa.SmallInteger(), nullable=False),
    sa.Column('source_csv_path', sa.String(length=512), nullable=True),
    sa.CheckConstraint("floor_median IS NULL OR floor_median <> 'NaN'::double precision", name=op.f('ck_pangenome_similarity_baseline__floor_median_is_not_nan')),
    sa.CheckConstraint("floor_p25 IS NULL OR floor_p25 <> 'NaN'::double precision", name=op.f('ck_pangenome_similarity_baseline__floor_p25_is_not_nan')),
    sa.CheckConstraint("floor_p75 IS NULL OR floor_p75 <> 'NaN'::double precision", name=op.f('ck_pangenome_similarity_baseline__floor_p75_is_not_nan')),
    sa.CheckConstraint("floor_p99 IS NULL OR floor_p99 <> 'NaN'::double precision", name=op.f('ck_pangenome_similarity_baseline__floor_p99_is_not_nan')),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_pangenome_similarity_baseline__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pangenome_similarity_baseline_id', name=op.f('pk_pangenome_similarity_baseline')),
    sa.UniqueConstraint('pangenome_id', 'representation', name=op.f('uq_pangenome_similarity_baseline__pangenome_id_representation'))
    )
    op.create_table('locus_nearest_locus',
    sa.Column('locus_nearest_locus_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locus_id', sa.BigInteger(), nullable=False),
    sa.Column('representation',
        postgresql.ENUM('ESM', 'BACFORMER', name='embeddingrepresentation', create_type=False),
        nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('neighbour_locus_id', sa.BigInteger(), nullable=False),
    sa.Column('cross_similarity', sa.Float(), nullable=True),
    sa.CheckConstraint("cross_similarity IS NULL OR cross_similarity <> 'NaN'::double precision", name=op.f('ck_locus_nearest_locus__cross_similarity_is_not_nan')),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_locus_nearest_locus__locus_id__locus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['neighbour_locus_id'], ['locus.locus_id'], name=op.f('fk_locus_nearest_locus__neighbour_locus_id__locus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_nearest_locus_id', name=op.f('pk_locus_nearest_locus')),
    sa.UniqueConstraint('locus_id', 'representation', 'rank', name=op.f('uq_locus_nearest_locus__locus_id_representation_rank'))
    )
    # ⚠ The unique constraint above indexes `locus_id`. `neighbour_locus_id` is a SECOND FK to the same
    # table and has none without this — a pangenome delete would scan every row per locus, the omission
    # that cost an 8-minute stall on `gene_locus_membership`.
    op.create_index('ix_locus_nearest_locus__neighbour_locus_id', 'locus_nearest_locus', ['neighbour_locus_id'], unique=False)
    op.create_table('locus_similarity',
    sa.Column('locus_similarity_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locus_id', sa.BigInteger(), nullable=False),
    sa.Column('representation',
        postgresql.ENUM('ESM', 'BACFORMER', name='embeddingrepresentation', create_type=False),
        nullable=False),
    sa.Column('within_similarity', sa.Float(), nullable=True),
    sa.Column('nearest_similarity', sa.Float(), nullable=True),
    sa.Column('weak_own_similarity', sa.Float(), nullable=True),
    sa.Column('weak_other_similarity', sa.Float(), nullable=True),
    sa.Column('own_neighbour_fraction', sa.Float(), nullable=True),
    sa.Column('separation_percentile', sa.Float(), nullable=True),
    sa.Column('weak_margin_percentile', sa.Float(), nullable=True),
    sa.Column('own_fraction_percentile', sa.Float(), nullable=True),
    sa.CheckConstraint("nearest_similarity IS NULL OR nearest_similarity <> 'NaN'::double precision", name=op.f('ck_locus_similarity__nearest_similarity_is_not_nan')),
    sa.CheckConstraint("own_fraction_percentile IS NULL OR own_fraction_percentile <> 'NaN'::double precision", name=op.f('ck_locus_similarity__own_fraction_percentile_is_not_nan')),
    sa.CheckConstraint("own_neighbour_fraction IS NULL OR own_neighbour_fraction <> 'NaN'::double precision", name=op.f('ck_locus_similarity__own_neighbour_fraction_is_not_nan')),
    sa.CheckConstraint("separation_percentile IS NULL OR separation_percentile <> 'NaN'::double precision", name=op.f('ck_locus_similarity__separation_percentile_is_not_nan')),
    sa.CheckConstraint("weak_margin_percentile IS NULL OR weak_margin_percentile <> 'NaN'::double precision", name=op.f('ck_locus_similarity__weak_margin_percentile_is_not_nan')),
    sa.CheckConstraint("weak_other_similarity IS NULL OR weak_other_similarity <> 'NaN'::double precision", name=op.f('ck_locus_similarity__weak_other_similarity_is_not_nan')),
    sa.CheckConstraint("weak_own_similarity IS NULL OR weak_own_similarity <> 'NaN'::double precision", name=op.f('ck_locus_similarity__weak_own_similarity_is_not_nan')),
    sa.CheckConstraint("within_similarity IS NULL OR within_similarity <> 'NaN'::double precision", name=op.f('ck_locus_similarity__within_similarity_is_not_nan')),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_locus_similarity__locus_id__locus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_similarity_id', name=op.f('pk_locus_similarity')),
    sa.UniqueConstraint('locus_id', 'representation', name=op.f('uq_locus_similarity__locus_id_representation'))
    )
    op.drop_table('locus_map_projection')
    op.drop_table('locus_embedding_geometry')
    op.drop_table('locus_map_scatter_sprite')
    op.drop_constraint(op.f('ck_locus__bacformer_nearest_medoid_distance_is_not_nan'), 'locus', type_='check')
    op.drop_constraint(op.f('ck_locus__bacformer_within_medoid_distance_is_not_nan'), 'locus', type_='check')
    op.drop_constraint(op.f('ck_locus__embed_within_over_nearest_is_not_nan'), 'locus', type_='check')
    op.drop_constraint(op.f('ck_locus__esm_nearest_medoid_distance_is_not_nan'), 'locus', type_='check')
    op.drop_constraint(op.f('ck_locus__esm_within_medoid_distance_is_not_nan'), 'locus', type_='check')
    op.drop_constraint(op.f('ck_locus__separation_percentile_bacformer_is_not_nan'), 'locus', type_='check')
    op.drop_constraint(op.f('ck_locus__separation_percentile_esm_is_not_nan'), 'locus', type_='check')
    op.drop_column('locus', 'bacformer_within_medoid_distance')
    op.drop_column('locus', 'esm_within_medoid_distance')
    op.drop_column('locus', 'esm_nearest_medoid_distance')
    op.drop_column('locus', 'separation_percentile_esm')
    op.drop_column('locus', 'embed_within_over_nearest')
    op.drop_column('locus', 'separation_percentile_bacformer')
    op.drop_column('locus', 'bacformer_nearest_medoid_distance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locus', sa.Column('bacformer_nearest_medoid_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locus', sa.Column('separation_percentile_bacformer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locus', sa.Column('embed_within_over_nearest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locus', sa.Column('separation_percentile_esm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locus', sa.Column('esm_nearest_medoid_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locus', sa.Column('esm_within_medoid_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locus', sa.Column('bacformer_within_medoid_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('ck_locus__separation_percentile_esm_is_not_nan'), 'locus', "separation_percentile_esm IS NULL OR separation_percentile_esm <> 'NaN'::double precision")
    op.create_check_constraint(op.f('ck_locus__separation_percentile_bacformer_is_not_nan'), 'locus', "separation_percentile_bacformer IS NULL OR separation_percentile_bacformer <> 'NaN'::double precision")
    op.create_check_constraint(op.f('ck_locus__esm_within_medoid_distance_is_not_nan'), 'locus', "esm_within_medoid_distance IS NULL OR esm_within_medoid_distance <> 'NaN'::double precision")
    op.create_check_constraint(op.f('ck_locus__esm_nearest_medoid_distance_is_not_nan'), 'locus', "esm_nearest_medoid_distance IS NULL OR esm_nearest_medoid_distance <> 'NaN'::double precision")
    op.create_check_constraint(op.f('ck_locus__embed_within_over_nearest_is_not_nan'), 'locus', "embed_within_over_nearest IS NULL OR embed_within_over_nearest <> 'NaN'::double precision")
    op.create_check_constraint(op.f('ck_locus__bacformer_within_medoid_distance_is_not_nan'), 'locus', "bacformer_within_medoid_distance IS NULL OR bacformer_within_medoid_distance <> 'NaN'::double precision")
    op.create_check_constraint(op.f('ck_locus__bacformer_nearest_medoid_distance_is_not_nan'), 'locus', "bacformer_nearest_medoid_distance IS NULL OR bacformer_nearest_medoid_distance <> 'NaN'::double precision")
    op.create_table('locus_map_scatter_sprite',
    sa.Column('locus_map_scatter_sprite_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pangenome_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('representation', postgresql.ENUM('ESM', 'BACFORMER', name='embeddingrepresentation', create_type=False),
        autoincrement=False, nullable=False),
    sa.Column('image_png', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('image_media_type', sa.VARCHAR(length=32), server_default=sa.text("'image/png'::character varying"), autoincrement=False, nullable=False),
    sa.Column('pixel_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewport_centre_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('viewport_centre_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('viewport_span', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dust_radius_pixels', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('alpha_per_locus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('plotted_locus_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unplotted_locus_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_digest', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_locus_map_scatter_sprite__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_map_scatter_sprite_id', name=op.f('pk_locus_map_scatter_sprite')),
    sa.UniqueConstraint('pangenome_id', 'representation', name=op.f('uq_locus_map_scatter_sprite__pangenome_id_representation'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('locus_embedding_geometry',
    sa.Column('locus_embedding_geometry_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('locus_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('representation', postgresql.ENUM('ESM', 'BACFORMER', name='embeddingrepresentation', create_type=False),
        autoincrement=False, nullable=False),
    sa.Column('map_x', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('map_y', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('nearest_locus_ordinals', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('pairwise_cosine_scaled', postgresql.ARRAY(sa.SMALLINT()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['locus_id'], ['locus.locus_id'], name=op.f('fk_locus_embedding_geometry__locus_id__locus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_embedding_geometry_id', name=op.f('pk_locus_embedding_geometry')),
    sa.UniqueConstraint('locus_id', 'representation', name=op.f('uq_locus_embedding_geometry__locus_id_representation'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('locus_map_projection',
    sa.Column('locus_map_projection_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pangenome_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('representation', postgresql.ENUM('ESM', 'BACFORMER', name='embeddingrepresentation', create_type=False),
        autoincrement=False, nullable=False),
    sa.Column('projection_method', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('requested_metric', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('neighbour_count', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('scale_centre_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scale_centre_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scale_span', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scale_unit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extent_min_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extent_min_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extent_max_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extent_max_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cos6_pair_order_version', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('cosine_scale_factor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_csv_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('null_bin_lower_edge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('null_bin_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('null_bin_counts', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('null_mean_cosine', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('separation_measurable_locus_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pangenome_id'], ['pangenome.pangenome_id'], name=op.f('fk_locus_map_projection__pangenome_id__pangenome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locus_map_projection_id', name=op.f('pk_locus_map_projection')),
    sa.UniqueConstraint('pangenome_id', 'representation', name=op.f('uq_locus_map_projection__pangenome_id_representation'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('locus_similarity')
    op.drop_index('ix_locus_nearest_locus__neighbour_locus_id', table_name='locus_nearest_locus')
    op.drop_table('locus_nearest_locus')
    op.drop_table('pangenome_similarity_baseline')
    # ### end Alembic commands ###
