"""the landing locus, the example chips, and the percentile denominator

Three columns for three numbers the page prints and the schema had nowhere to put. All pure
additions, so autogenerate's output stands unedited.

1/2. `pangenome.landing_locus_id` and `example_locus_ids`. These were assumed derivable from
     `locus.interest_score` and are not: `render_page.landing` FILTERS the ranking for the first
     locus whose modal Bakta symbol is `fimA`, so a stranger opens on something they may recognise
     rather than on whatever scored highest that week. The preference actually fires on both
     published catalogues — ecoli opens on 2811 and kp on 1098, and neither is its own
     `examples[0]`. Left uncomputed, the page would open somewhere else than it does today.

     ⚠ They were a render-time payload mutation, which is how every site page deployed
     2026-08-20..2026-08-25 opened on locus 0 with no reference names: a caller serialised the
     payload before `render` had mutated it, and nothing failed. As stored columns that is not
     expressible.

3.   `locus_map_projection.separation_measurable_locus_count` — the other half of the card's
     sentence *"p12 of 12,104 loci"*. The percentile is a midrank over the MEASURABLE loci, not
     over the catalogue, and both halves are assertions, so the denominator needs a home. This
     table's grain is already (pangenome, representation), which is the denominator's grain too.

Revision ID: a92d77dbc4c5
Revises: 3bb9b090284b
Create Date: 2026-09-04 19:30:35.527261
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a92d77dbc4c5'
down_revision: str | None = '3bb9b090284b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locus_map_projection', sa.Column('separation_measurable_locus_count', sa.Integer(), nullable=True))
    op.add_column('pangenome', sa.Column('landing_locus_id', sa.BigInteger(), nullable=True))
    op.add_column('pangenome', sa.Column('example_locus_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pangenome', 'example_locus_ids')
    op.drop_column('pangenome', 'landing_locus_id')
    op.drop_column('locus_map_projection', 'separation_measurable_locus_count')
    # ### end Alembic commands ###
